//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramBotBase.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramBotBase.Localizations.Localizations.en", typeof(Localizations_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string ButtonGrid_Back {
            get {
                return ResourceManager.GetString("ButtonGrid_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all.
        /// </summary>
        internal static string ButtonGrid_CheckAll {
            get {
                return ResourceManager.GetString("ButtonGrid_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string ButtonGrid_CurrentPage {
            get {
                return ResourceManager.GetString("ButtonGrid_CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶️.
        /// </summary>
        internal static string ButtonGrid_NextPage {
            get {
                return ResourceManager.GetString("ButtonGrid_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items..
        /// </summary>
        internal static string ButtonGrid_NoItems {
            get {
                return ResourceManager.GetString("ButtonGrid_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◀️.
        /// </summary>
        internal static string ButtonGrid_PreviousPage {
            get {
                return ResourceManager.GetString("ButtonGrid_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Send a message to filter the list. Click the 🔍 to reset the filter..
        /// </summary>
        internal static string ButtonGrid_SearchFeature {
            get {
                return ResourceManager.GetString("ButtonGrid_SearchFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string ButtonGrid_Title {
            get {
                return ResourceManager.GetString("ButtonGrid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck all.
        /// </summary>
        internal static string ButtonGrid_UncheckAll {
            get {
                return ResourceManager.GetString("ButtonGrid_UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶️.
        /// </summary>
        internal static string CalendarPicker_NextPage {
            get {
                return ResourceManager.GetString("CalendarPicker_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◀️.
        /// </summary>
        internal static string CalendarPicker_PreviousPage {
            get {
                return ResourceManager.GetString("CalendarPicker_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick date.
        /// </summary>
        internal static string CalendarPicker_Title {
            get {
                return ResourceManager.GetString("CalendarPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string Foo {
            get {
                return ResourceManager.GetString("Foo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosen.
        /// </summary>
        internal static string MultiToggleButton_Changed {
            get {
                return ResourceManager.GetString("MultiToggleButton_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅.
        /// </summary>
        internal static string MultiToggleButton_SelectedIcon {
            get {
                return ResourceManager.GetString("MultiToggleButton_SelectedIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Toggle.
        /// </summary>
        internal static string MultiToggleButton_Title {
            get {
                return ResourceManager.GetString("MultiToggleButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string PromptDialog_Back {
            get {
                return ResourceManager.GetString("PromptDialog_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosen.
        /// </summary>
        internal static string ToggleButton_Changed {
            get {
                return ResourceManager.GetString("ToggleButton_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string ToggleButton_Off {
            get {
                return ResourceManager.GetString("ToggleButton_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚪.
        /// </summary>
        internal static string ToggleButton_OffIcon {
            get {
                return ResourceManager.GetString("ToggleButton_OffIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ToggleButton_On {
            get {
                return ResourceManager.GetString("ToggleButton_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚫.
        /// </summary>
        internal static string ToggleButton_OnIcon {
            get {
                return ResourceManager.GetString("ToggleButton_OnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string ToggleButton_Title {
            get {
                return ResourceManager.GetString("ToggleButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔼 level up.
        /// </summary>
        internal static string TreeView_LevelUp {
            get {
                return ResourceManager.GetString("TreeView_LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select node.
        /// </summary>
        internal static string TreeView_Title {
            get {
                return ResourceManager.GetString("TreeView_Title", resourceCulture);
            }
        }
    }
}
