//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramBotBase.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramBotBase.Localizations.Localizations.de", typeof(Localizations_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string ButtonGrid_Back {
            get {
                return ResourceManager.GetString("ButtonGrid_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle auswählen.
        /// </summary>
        public static string ButtonGrid_CheckAll {
            get {
                return ResourceManager.GetString("ButtonGrid_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seite {0} von {1}.
        /// </summary>
        public static string ButtonGrid_CurrentPage {
            get {
                return ResourceManager.GetString("ButtonGrid_CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶️.
        /// </summary>
        public static string ButtonGrid_NextPage {
            get {
                return ResourceManager.GetString("ButtonGrid_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind keine Einträge vorhanden..
        /// </summary>
        public static string ButtonGrid_NoItems {
            get {
                return ResourceManager.GetString("ButtonGrid_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◀️.
        /// </summary>
        public static string ButtonGrid_PreviousPage {
            get {
                return ResourceManager.GetString("ButtonGrid_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Sende eine Nachricht um die Liste zu filtern. Klicke die 🔍 um den Filter zurückzusetzen..
        /// </summary>
        public static string ButtonGrid_SearchFeature {
            get {
                return ResourceManager.GetString("ButtonGrid_SearchFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü.
        /// </summary>
        public static string ButtonGrid_Title {
            get {
                return ResourceManager.GetString("ButtonGrid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine auswählen.
        /// </summary>
        public static string ButtonGrid_UncheckAll {
            get {
                return ResourceManager.GetString("ButtonGrid_UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶️.
        /// </summary>
        public static string CalendarPicker_NextPage {
            get {
                return ResourceManager.GetString("CalendarPicker_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◀️.
        /// </summary>
        public static string CalendarPicker_PreviousPage {
            get {
                return ResourceManager.GetString("CalendarPicker_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum auswählen.
        /// </summary>
        public static string CalendarPicker_Title {
            get {
                return ResourceManager.GetString("CalendarPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch (German).
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählt.
        /// </summary>
        public static string MultiToggleButton_Changed {
            get {
                return ResourceManager.GetString("MultiToggleButton_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅.
        /// </summary>
        public static string MultiToggleButton_SelectedIcon {
            get {
                return ResourceManager.GetString("MultiToggleButton_SelectedIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehrfach-Schalter.
        /// </summary>
        public static string MultiToggleButton_Title {
            get {
                return ResourceManager.GetString("MultiToggleButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string PromptDialog_Back {
            get {
                return ResourceManager.GetString("PromptDialog_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählt.
        /// </summary>
        public static string ToggleButton_Changed {
            get {
                return ResourceManager.GetString("ToggleButton_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus.
        /// </summary>
        public static string ToggleButton_Off {
            get {
                return ResourceManager.GetString("ToggleButton_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚪.
        /// </summary>
        public static string ToggleButton_OffIcon {
            get {
                return ResourceManager.GetString("ToggleButton_OffIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An.
        /// </summary>
        public static string ToggleButton_On {
            get {
                return ResourceManager.GetString("ToggleButton_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚫.
        /// </summary>
        public static string ToggleButton_OnIcon {
            get {
                return ResourceManager.GetString("ToggleButton_OnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schalter.
        /// </summary>
        public static string ToggleButton_Title {
            get {
                return ResourceManager.GetString("ToggleButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔼 Stufe hoch.
        /// </summary>
        public static string TreeView_LevelUp {
            get {
                return ResourceManager.GetString("TreeView_LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knoten auswählen.
        /// </summary>
        public static string TreeView_Title {
            get {
                return ResourceManager.GetString("TreeView_Title", resourceCulture);
            }
        }
    }
}
